// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello World';
//
//   build() {
//
//     Column() {
//       Text('VIP')
//         .backgroundColor(Color.Orange)
//         .borderRadius({
//           topLeft: 10,
//           bottomRight: 10
//         })
//         .width(40)
//         .height(20)
//         .zIndex(99)
//         .position({
//           x: 100,
//           y: 0
//         })
//         .border({
//           width: 2,
//           color: '#FFD252',
//           style: BorderStyle.Solid
//         })
//         .fontStyle(FontStyle.Italic)
//         .fontSize(14)
//         .fontWeight(700)
//         .padding({
//           left: 5
//         })
//
//       Image($r('app.media.cat')).width(160).height(240).borderRadius(10)
//       Row() {
//         Image($r('app.media.avatar')).width(40).height(40)
//         Text('飞狗MOCO').fontSize(20).fontWeight(FontWeight.Bold).margin({
//           left: 3
//         })
//       }.backgroundColor(Color.White).width(160).padding(5)
//     }
//     .backgroundColor(Color.Pink).height('100%').width('100%')
//
//   }
// }
//
